Bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: oef-stage
      dataset: TestRecoursePlanner
      threads: 2
      timeout_seconds: 300
      priority: interactive

     keyfile_sjon:
        type: "service_account"
        project_id: "oef-stage"
        private_key_id: "58d8b62f3603679530f14a3eab8a1483d4c1af54"
        private_key: 
        client_email: "dbt-222@oef-stage.iam.gserviceaccount.com"
        client_id: "113288976275918515776"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/dbt-222%40oef-stage.iam.gserviceaccount.com"
